#include <Weather.idl>
#include <Config.idl>
#include <Schedule.idl>
#include <UvegHaz.idl>

enum Decision { OPEN, CLOSE };

struct DecisionInfo {
    unsigned long decisionTS;
    Decision decision;
    Config config;
    Weather lastWeather;
    Schedule lastSchedule;
    UvegHaz lastHumidity;
};